services:
  - type: web
    name: LMS-Backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 run_server:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: MAIL_USERNAME
        value: "your-email@example.com"
      - key: MAIL_PASSWORD
        value: "your-email-password"
  - type: worker
    name: Celery-Worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_config.celery worker --loglevel=info"
  - type: redis
    name: Redis
    plan: free
  - type: postgresql
    name: lms-db
    plan: free
